excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://svscomics.github.io
title: Porn Comics & Hentai
email: contact@svscomics.org
author: Jane Smith
description: Everything I know about porn comics and hentai manga
paginate: 3
google_analytics: 